### ISSUE TITLE
Publish beancount-ethereum-importer to make using it easier

### ISSUE THREAD

**Issue by owodunni** [xuhcc/beancount-ethereum-importer#7]
I want to be able to use the beancount-ethereum-importer, to do so I want to be able to depend on it in a simple way.

To do so I suggest publishing it to https://pypi.org/ from github actions when a github release is created.

**Comment by xuhcc** [comment]
https://pypi.org/project/beancount-ethereum/1.4.2/

**Comment by xuhcc** [comment]
I've fixed the package description: https://pypi.org/project/beancount-ethereum/1.4.3/
